FROM tensorflow/tensorflow:latest

#set noninteractive to avoid timezone error during building
ARG DEBIAN_FRONTEND=noninteractive

#execute necessary commands for installing additional packages:
#   -software-properties-common for add-apt-repository and gcc
#   -ppa:deadsnakes/ppa for installing python3.x on ubuntu (in this case python3.9)

RUN apt-get update 

RUN apt-get install -y software-properties-common gcc
    
RUN add-apt-repository -y ppa:deadsnakes/ppa

RUN apt-get update && apt-get install -y python3.8 python3-distutils python3-pip python3-apt

RUN python3 -m pip install --upgrade pip

RUN apt -y install libportaudio2

#individual requirement installation
RUN pip3 install mlflow==2.1.1
RUN pip3 install dagshub==0.2.12
RUN pip3 install -q tflite-model-maker

WORKDIR /app
# Create directories for dataset, model, and training code
RUN mkdir data model training

# Create placeholder files for train.py
RUN touch training/train.py

# Set the working directory
WORKDIR /app/training

# Copy requirements.txt and install dependencies
#   -this is done to check version mismatch between dockerfile and requirements.txt libraries

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY train.py .

ENTRYPOINT [ "python", "train.py" ]




