FROM nvidia/cuda:11.2.0-cudnn8-runtime-ubuntu18.04

#set noninteractive to avoid timezone error during building
ARG DEBIAN_FRONTEND=noninteractive

#execute necessary commands for installing additional packages:
#   -software-properties-common for add-apt-repository and gcc
#   -ppa:deadsnakes/ppa for installing python3.x on ubuntu (in this case python3.9)
RUN apt-get update && apt-get install -y software-properties-common gcc && \
    add-apt-repository -y ppa:deadsnakes/ppa

RUN apt-get update && apt-get install -y python3.9 python3-distutils python3-pip python3-apt