FROM ubuntu:20.04

ARG NEEDRESTART_MODE=a
ARG DEBIAN_FRONTEND=noninteractive

ARG DEBIAN_PRIORITY=critical

# initialization
RUN apt update
RUN apt upgrade -y

# python
RUN apt-get update && apt-get install -y software-properties-common gcc && \
    add-apt-repository -y ppa:deadsnakes/ppa

RUN apt-get update && apt-get install -y python3.7 python3-distutils python3-pip python3-apt

RUN pip3 install -r requirements.txt

# dataset

RUN wget https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
tar -xvf cifar-10-python.tar.gz

# load 
RUN python3 perf_samples_loader.py

# train + test
RUN python3 train.py
RUN python3 test.py

# tfliter
RUN python3 model_converter.py
RUN python3 tflite_test.py



